language: go

go:
  - "1.10"

install:
  - go get -race -t -v ./...
  - go get github.com/modocache/gover
  - go get github.com/mattn/goveralls
script:
  - go test -race -v ./...
  - go build
  - gover
  - goveralls -coverprofile=gover.coverprofile -service=travis-ci
